---
- name: create directory
  shell: mkdir java chdir=/opt
- name: Download JDK from S3
  get_url:
    url:  http://euo.s3-website-us-east-1.amazonaws.com/Software/JAVA/jdk-8u91-linux-x64.tar.gz
    dest: /opt/java
    mode: 0754      
- name: Extract java 
  shell: tar xvf jdk-8u91-linux-x64.tar.gz chdir=/opt/java/
- name: Set java path
  shell: echo export JAVA_HOME=/opt/java/jdk1.8.0_91 export PATH=$PATH:$JAVA_HOME/bin > /etc/profile.d/java.sh
- name: apply java path
  shell: source /etc/profile.d/java.sh  
- name: make java1.8 as default
  shell: update-alternatives --install "/usr/bin/java" "java" "/opt/java/jdk1.8.0_91/bin/java" 1
- name: make java1.8 as default
  shell: update-alternatives --install "/usr/bin/javac" "javac" "/opt/java/jdk1.8.0_91/bin/javac" 1
- name: make java1.8 as default
  shell: update-alternatives --set java /opt/java/jdk1.8.0_91/bin/java
- name: make java1.8 as default
  shell: update-alternatives --set javac /opt/java/jdk1.8.0_91/bin/javac
- name: make java1.8 as default
  shell: source /etc/profile

